version: "3.8"

services:
  neo4j:
    image: neo4j:5.26.1
    environment:
      - NEO4J_AUTH=neo4j:${NEO4J_PASSWORD}
      - JAVA_HOME=/usr/lib/jvm/java-21-openjdk
    volumes:
      - ./neo4j/conf/neo4j.conf:/var/lib/neo4j/conf/neo4j.conf
      - ./neo4j/plugins:/var/lib/neo4j/plugins
      - neo4j_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_HOST=neo4j
      - NEO4J_HTTP_PORT=7474
      - NEO4J_BOLT_PORT=7687
      - NEO4J_USER=neo4j
    depends_on:
      - neo4j
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  neo4j_data: